### ISSUE TITLE
Method `isEU()` is undefined

### ISSUE THREAD

**Issue by Miklelottesen** [Youfront/is-eu#1]
`import { isEU } from 'is-eu'` and `isEU(someCountryCode)` (as indicated in the documentation) fails, as `isEU` is undefined.

Fixable by importing and calling `isEu` (lowercase 'u') instead, as that is the name of the exported function in the library.

**Comment by andershagbard** [comment]
Thanks for this. It should be `IsEU`. I'll update it asap.

**Comment by andershagbard** [comment]
Fixed in https://github.com/Youfront/is-eu/commit/05417b07bfa3dd310ef5803fd35805d943399237
